name: Terraform

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Azure CLI
        run: sudo apt-get install azure-cli

      - name: Install pwsh and Azure PowerShell
        run: |
          sudo apt-get install -y powershell
          pwsh -c Install-Module -Name Az -Scope CurrentUser -Repository PSGallery -Force

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          auth-type: servicePrincipal
      
      - name: Terraform Format
        run: terraform fmt -check

